# =============================================================================
# HOMELAB ANSIBLE INVENTORY
# =============================================================================
# 
# This inventory file defines all the hosts in the homelab infrastructure.
#
# =============================================================================

all:
    children:
        ubuntu_servers:
            hosts:
                homelab-server:
                    ansible_host: 192.168.1.20
                    ansible_user: yash
                    ansible_become: yes
        proxmox_hosts:
            hosts:
                proxmox-host:
                    ansible_host: 192.168.1.10
                    ansible_user: admin
                    ansible_become: yes
        opnsense_hosts:
            hosts:
                opnsense-firewall:
                    ansible_host: 192.168.1.1
                    ansible_user: root
                    ansible_become: yes
        pangolin_hosts:
            hosts:
                pangolin-vps:
                    ansible_host: "{{ vault_pangolin_vps_ip }}"
                    ansible_user: "{{ vault_pangolin_vps_user }}"
                    ansible_become: yes
                    

# =============================================================================
# TESTING CONNECTIVITY
# =============================================================================
#
# Test connection to all hosts:
# ansible all -i inventory/homelab.yml -m ping
#
# Test specific group:
# ansible ubuntu_servers -i inventory/homelab.yml -m ping
#
# Test with vault password:
# ansible all -i inventory/homelab.yml -m ping --ask-vault-pass
#
# Test pangolin VPS specifically:
# ansible pangolin-vps -i inventory/homelab.yml -m ping --ask-vault-pass
#
# =============================================================================
